python_alphabet = {
    "A": "Assignment",
    "B": "Boolean",
    "C": "Class",
    "D": "Dictionary",
    "E": "Exception",
    "F": "Function",
    "G": "Global",
    "H": "Import",
    "I": "Integer",
    "J": "Join",
    "K": "Keyword",
    "L": "List",
    "M": "Method",
    "N": "None",
    "O": "Operator",
    "P": "Print",
    "Q": "Queue",
    "R": "Return",
    "S": "String",
    "T": "Tuple",
    "U": "Unicode",
    "V": "Variable",
    "W": "While",
    "X": "Execute",
    "Y": "Yield",
    "Z": "Zip",
}
